version: '3.9'

services:
  backend:
    container_name: nest-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - archivematica_net

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preservacaoDigital
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - archivematica_net

volumes:
  db_data:

networks:
  archivematica_net:
    external: true
